### ISSUE TITLE
specifying an audit-mode in a machine's run_list fails the provisioning run.

### ISSUE THREAD

**Issue by ricardolupo** [chef/chef-provisioning#393]
When I have an audit-mode recipe as part of my run_list in a provisioning recipe, the provisioning run stack traces with a generic

The audit-mode recipe is designed to intentionally fail audits, but as of chef-client 12.4.1, audit failures are not supposed to break a chef-client run; merely report that there are audit items that need remediation.

**Comment by galenemery** [comment]
The provisioned node will report back to Chef Server and analytics that it failed audit, but not converge.

Running chef-client manually does not result in an error on the node.

However the provisioner node fails and does not continue its run_list.

**Comment by tyler-ball** [comment]
Reference from #387:

```
================================================================================
Error executing action `converge` on resource 'machine_batch[default]'
================================================================================

RuntimeError
------------
Error: command 'chef-client -l info' exited with code 1.
```

This is due to:

```
 Chef Client finished, 20/24 resources updated in 39.348871933 seconds
   2/4 controls succeeded
```

We shouldn't fail on audit failures.

This is using:
chef-provisioning (1.2.0)
chef-provisioning-aws (1.2.1)
Chef Development Kit Version: 0.7.0.rc.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.1

Provisioning to AWS.  Chef-Server 12 (also running in AWS)

**Comment by tyler-ball** [comment]
Okay, I think I understand the issue - you want the provisioner workstation (hereafter referred to as just workstation) to complete its run_list, even when a `machine` (or `machine_batch`) resource spins up a node that runs an audit_recipe which fails.

Am I understanding that correctly?

**Comment by ricardolupo** [comment]
Yes!

**Comment by tyler-ball** [comment]
gist showing an example recipe and output from provisioning run - https://gist.github.com/tyler-ball/a9cbed07a9a8cbcbb19a

**Comment by tyler-ball** [comment]
@ricardolupo Audits are not performed until after the convergence, so even if there is an audit that fails it will occur after all the other resources have converged.  For example, if a provisioned node has the run_list `appserver::app, audits::default, appserver::config` and the `audits::default` recipe was full of failing `control_group`s then the `app` and `config` recipes will still be ran fully before the `control_group`s are ran.

The issue I am seeing now (and the reason I opened https://github.com/chef/chef-provisioning/pull/414) is because failing audits are returning a non-zero exit code which the provisioning workstation interprets as a failure and stops performing the rest of _its_ run_list.  My PR addresses that by adding an option for ignoring provisioned node failures and continuing the rest of the provisioning workstation run_list.

That PR also means that if you have 3 machines in a `machine_batch` and you add the `ignore_failure` converge option to them, no 1 failure will fail the entire machine_batch.  Does that support your request?

**Comment by ricardolupo** [comment]
@tyler-ball would audits also be performed after convergence if the audit recipes are at the beginning of the run_list?

I'm ok with allowing the machines to converge on audit failure for all of the machines in a `machine_batch`). Since audit mode would then report failures on the next converge anyway, users will get the visibility post-provisioning

**Comment by tyler-ball** [comment]
> would audits also be performed after convergence if the audit recipes are at the beginning of the run_list?

Yes (unless something changed since the last time I looked at it).

**Comment by galenemery** [comment]
As we discussed, ideally I'd like 'ignore_failure' and  'ignore_audit_failure' options so we can specifically ignore one or the other.

But the first step is getting the logic in there to ignore any failures.  Then we can iterate on that.

I think there will be customers who don't want things to continue to be provisioned if any system fails its audit mode and supporting that makes sense, but I also suspect at least initially that'll be the minority.
